version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # root for monorepo workspace
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "pnpm" # ignore pnpm updates to manage manually
    groups:
      dev-dependencies:
        patterns:
          - "eslint*"
          - "typescript"
          - "jest"
          - "prettier"
          - "husky"
          - "commitlint"
          - "lint-staged"
          - "tailwind*"
        update-types:
          - "major"
          - "minor"
          - "patch"
      dependencies:
        patterns:
          - "*"
          - "!eslint*"
          - "!typescript"
          - "!jest"
          - "!prettier"
          - "!husky"
          - "!commitlint"
          - "!lint-staged"
          - "!tailwind*"
        update-types:
          - "major"
          - "minor"
          - "patch"